### ISSUE TITLE
buildKKRMatrix_gpu

### ISSUE THREAD

**Issue by xinye83** [mstsuite/lsms#14]
The prototype for `buildKKRMatrix_gpu` in line 45 of `src/Accelerator/buildKKRMatrix_gpu.hpp` does not match the definition in line 286 of `src/Accelerator/buildKKRMatrix_gpu.cu`, caused an error when compiling.

**Comment by xinye83** [comment]
Same issue with `buildKKRMatrix_gpu_opaque`

**Comment by meisenbach** [comment]
There is also a bug in buildKKRMatrix_gpu that prevents it to function for general systems. The routine is currently in the process of being rewritten completely.

**Comment by meisenbach** [comment]
buildKKRMatrix_gpu has been replaced by buildKKRMatrix_CUDA which solves the issues. The old build options are to be removed and the build algorithm can no be selected in the input file.
