### ISSUE TITLE
Tutorial on output files

### ISSUE THREAD

**Issue by odbadrakh** [mstsuite/lsms#30]
p.h.shi@fudan.edu.cn

I am a PhD candidate from Institute of Modern Physics of Fudan university.
 
Recently I've read the paper 'Engineering atomic-level complexity in high-entropy and complex concentrated alloys', focusing on the LSMS method. I've attempted to understand the reasoning process( in the following picture) and method of implementation about the atomic-level pressure. However, I am incapable of finding information in the Output file given by LSMS code from the github.
 
Could you please guide me on the tutorial on the LSMS method?
Panhua Shi

**Comment by odbadrakh** [comment]
Markus and Yang, 
Could you please help in making the output file tutorial accessible? Thank you

**Comment by meisenbach** [comment]
I just uploaded the slides for the LSMS tutorial in the doc directory.
